@extends('layouts.main')

@section('title', 'Page Title')

@section('content')
    <div class="row">
        <div class="shadow p-3 mb-5 rounded bg-light">
            <h2>OrthoGNC: Accurate Identification of Orthologs based on Gene Neighborhood Conservation</h2>
            <p></p><p></p><p></p>
            <h4>Dscription</h4>
            <p>Soheil Jahangiri-Tazehkand, Changiz Eslahchi, Limsoon Wong </p>
            <p>
                Orthology relations can be used to transfer annotations from one gene (or protein) to another. Hence, detecting orthology relations has become an important task in the post-genomic era. Various genomic events--- duplication, horizontal gene transfer, etc. ---can cause erroneous assignment of orthology relations. Gene neighborhood information can be used to resolve many ambiguities in orthology inference. Here we present OrthoGNC, a software for accurately predicting pairwise orthology relations based on gene neighborhood conservation. Our experiments on simulated and real data reveal high accuracy of OrthoGNC. In addition to orthology detection, OrthoGNC can be employed to investigate the conservation of genomic context among potential orthologs detected by other methods. OrthoGNC is free and available online at:
                <a href="http://bs.ipm.ir/softwares/orthognc">http://bs.ipm.ir/softwares/orthognc</a> and

                <a href="http://tinyurl.com/orthoGNC">http://tinyurl.com/orthoGNC</a>.
            </p>
            <div>
                <a href="http://bs.ipm.ac.ir/softwares/orthognc/OrthoGNC.rar">OrthoGNC binary</a>
                <br />
                <a href="http://bs.ipm.ac.ir/softwares/orthognc/UserGuide.txt">User's Guide</a>
                <br />
                <a href="http://bs.ipm.ac.ir/softwares/orthognc/8mycobacterium.rar">8 Mycobacterium data set (fastA files)</a>
                <br />
                <a href="http://bs.ipm.ac.ir/softwares/orthognc/sim_data.rar">30 simulated species (fastA files)</a>
                <br />
                <a href="http://bs.ipm.ac.ir/softwares/orthognc/ALF_output.rar">Output of ALF web serivce.</a>
                (This file contains the complete archive generated by ALF web service. It contains fastA files, MSA files, Orthology matrices, etc.)

                </span></p>
                <p>If you have any questions regarding the software, please contact s(dot)jahangiri(dot)cs(at sign)gmail.com.</p>
            </div>
        </div>
    </div>
    </div>
@endsection